# Use an official Python runtime as a parent image
FROM ubuntu:18.04

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN export LANG=C.UTF-8
# update repo and
# Install any needed packages specified in requirements.txt
RUN apt update -y && \
    apt install -y python3-pip git curl && \
    pip3 install . && \
    pip3 install -r requirements.txt

ENV target_dir /app/alpaka

RUN ls -l ${target_dir}
RUN /bin/bash ${target_dir}/tests/test_all.sh

RUN echo " ------ UNINSTALL TEST ------"
RUN curl -s https://raw.githubusercontent.com/ProjectVellum/vellum-utils/master/uninstall_test.sh | bash -s flask_fat flask_fat